### ISSUE TITLE
Loading Envelope failed

### ISSUE THREAD

**Issue by jacobburrell** [bryall/fava-envelope#10]
When trying to setup fava-envelope, I recieve the following error message:
```
fava_envelope/modules/beancount_envelope.py", line 136, in envelope_tables
    self.income_df.loc["Overspent", prev_month] + \
TypeError: unsupported operand type(s) for +: 'float' and 'decimal.Decimal'
```

**Comment by bryall** [comment]
thanks for reporting the issue, I will take a look at this when I can

**Comment by bryall** [comment]
sorry for the delay, got caught up in some other projects, I think I found some bugs causing some of these issues

closing this, please make a new issue if still having problems
