### ISSUE TITLE
Extension url not loading

### ISSUE THREAD

**Issue by SSPJ** [bryall/fava-envelope#15]
I installed globally using `sudo pip3 install fava-envelope`. Fava is also installed globally. The extension link shows up in Fava, but clicking it produces a 404. I tried running fava in debug mode, but got no further log messages.

```
"GET /<...>/extension/EnvelopeBudget/ HTTP/1.1" 404 -
```

I am using Python 3.8 on Ubuntu 20.04.

**Comment by Zburatorul** [comment]
I'm having the same issue.

**Comment by Zburatorul** [comment]
In my case the issue was solved by setting up an actual budget, as explained on the main page of the project.
(I had previous only inserted the extension import statement into my journal file)

**Comment by SSPJ** [comment]
Confirming. That does seem to have gotten me further.

Unfortunately, I am now getting a type error. Will come back to this if/when time permits.

**Comment by mcbloch** [comment]
I get the same error, but I did add all the lines suggested in the README (and checked that they correspond to valid accounts I have).

Is there a good way to debug this issue? Fava does not give any error in its output.

**Comment by bryall** [comment]
i assume there is some setting not acting properly.  you can use python's breakpoints to trace the code to see where it is going wrong, or provide a simple journal file to reproduce the issue. 

as far as I know there is no way for a extension to add errors to fava,

I will look into this in the new year, sorry I have been busy working on a language server protocol for beancount and not have given this project any attention for a while

**Comment by bryall** [comment]
sorry for the delay, got caught up in some other projects, I think I found some bugs causing some of these issues

closing this, please make a new issue if still having problems
