### ISSUE TITLE
404 for "Envelope budget" link in Fava sidebar 

### ISSUE THREAD

**Issue by andrewebdev** [bryall/fava-envelope#9]
Not sure if this is a bug or a newbie mistake by me (only migrated from ledger to beancount this week)

When I click "Envelop Budger" in the sidebar, I get a red error message pop up because of parsing error. This is because the response is a 404.

Am I missing something else that needs installed, configured or some invalid path, or could this be a legit bug?

EDIT: I removed the previous traceback since that was related to another error. I still cannot access the page however.

**Comment by jpluscplusm** [comment]
I also get this 404 out of the box. I'm going to dig further, but for the record here's the setup that results in this error:

```
$ pip3 freeze | grep -i -e fava -e beancount -e flask
beancount==2.3.0
fava==1.15
fava-envelope==0.5
Flask==1.1.2
Flask-Babel==1.0.0
$ python --version
Python 3.7.3
$ cat /etc/debian_version 
10.4
$ uname -s -m -o
Linux x86_64 GNU/Linux
```

Here's a minimal reproducer:

```test.beancount
option "operating_currency" "USD"
2020-01-01 custom "fava-extension" "fava_envelope" "{}"
2020-01-01 custom "envelope" "start date" "2020-01"
2020-01-01 custom "envelope" "budget account" "Assets:Current"
2020-01-01 custom "envelope" "mapping" "Expenses:Food:*" "Expenses:Food"
2020-01-01 open Expenses:Food
2020-01-01 open Equity:Opening-Balances
2020-01-01 open Assets:Current
2020-01-01 * "Opening balances"
        Equity:Opening-Balances
        Assets:Current                  1000 USD
2020-02-01 custom "envelope" "allocate" "Expenses:Food" 100.00
```

This produces the following fava debug log when accessing the page linked from the sidebar (http://localhost:5000/beancount/extension/EnvelopeBudget/)

```fava -d test.beancount
127.0.0.1 - - [20/Jul/2020 15:14:23] "GET /beancount/extension/EnvelopeBudget/ HTTP/1.1" 404 -
```

The 404 source, if it helps hone in on the cause, is:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by egetzner** [comment]
#11 should fix the minimal example by @jpluscplusm 
Months with no income entries cause the error.
